name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Verify gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "These files are not formatted:"
            echo "$files"
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Test with race detector and coverage
        run: |
          go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
